### PR TITLE
I give background color to h1

### PR DESCRIPTION
**Pull request by himanshujaidka**
Screenshot (693)

### CODE REVIEW

**Comment by ilyas-it83** [comment]
Hi @himanshujaidka, currently the H1 is in white background, what do you propose to change?

comparecloud

**Comment by himanshujaidka** [comment]
Actually I am fresher and want to contribute. So, I found that h1 become more attractive by applying background-color.

**Comment by himanshujaidka** [comment]
Pls, take some action or let me know if I did some wrong thing ;)

**Comment by ilyas-it83** [comment]
I personally think the white background is neat and clean, so its better to leave it this way. Sorry for the delayed response, but i appreciate your contributions and additional proposal to further simplify the UX.

**Pull request closed without merging**
