### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by iamabrom**
- Grammatical correction: updated category of "Security & Identity, Compliance" to "Security, Identity & Compliance"
- Changed "Mobile Services: Web/Mobile Authentication Services" to "Security, Identity & Compliance: Customer Identity and Access Management"
- Moved Oracle's "Mobile Hub" offering to the Mobile Services category.
- Added GCP's additional CIAM offering "Identity Platform" to the newly created CIAM category

### CODE REVIEW

**Comment by iamabrom** [comment]
#234

**Comment by iamabrom** [comment]
Hi @ilyas-it83, is there anything you'd rather have me change back?

**Comment by ilyas-it83** [comment]
Please check the issues for outstanding items and ideas please.

**Comment by iamabrom** [comment]
@ilyas-it83 Sorry, to be more clear- you closed the PR with no merge. So I was asking if there's something you didn't agree with in the PR. Also, this PR addresses #234.

**Review by ilyas-it83 — APPROVED** [review]

**Pull request merged**
