### PR TITLE
Create huawei

### PR DESCRIPTION
**Pull request by jairomv**

### CODE REVIEW

**Comment by GuruCharan94** [comment]
@ilyas-it83 , do you have plans to add and in future maintain Huawei cloud offerings.
@jairomv , while I appreciate the idea, I think it is better to get Ilyas' plans for the site. I don't want us to be in the situation to reject a big PR because it is not in the scope. 

Thanks

**Comment by jairomv** [comment]
I can share the information (icons, names, URLs direct to each service) that I already collected.
I have no enough experience using GitHub; but with your guidance I could do some advances.

**Comment by ilyas-it83** [comment]
No. Not at this moment.... The site plans to include only the players featured in the Gartner  Magic Quadrant for the public cloud. Gartner does a fantastic job of evaluating the cloud providers with multiple criteria's, so we also baseline based on thier definition.
https://pages.awscloud.com/Gartner-Magic-Quadrant-for-Infrastructure-as-a-Service-Worldwide.html

**Comment by jairomv** [comment]
Thanks Ilyas for your answer. The reason is very clear. Could I count with your authorization in order to use the current code and to publish the updated version on other web page?

**Comment by ilyas-it83** [comment]
Yes @jairomv, please use with some mention to the original repo and the site.

**Comment by ilyas-it83** [comment]
As per the conversation, closing this PR without merging.

**Pull request closed without merging**
