### PR TITLE
GCP BigTable url fix

### PR DESCRIPTION
**Pull request by davidkhala**
BigTable url is case sensitive

https://cloud.google.com/Bigtable/ page is 404 not found

### CODE REVIEW

**Review by iamabrom — APPROVED** [review]
checked and validated the updated link is correct

**Comment by ilyas-it83** [comment]
Sorry for the delay @davidkhala  @iamabrom

**Comment by davidkhala** [comment]
@ilyas-it83 It was closed without merge. Will you do in seperated commits?

**Review by ilyas-it83 — COMMENTED** [review]
Reviewed

**Review by ilyas-it83 — APPROVED** [review]

**Pull request merged**
